name: chat_bot_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  animate_do: ^4.2.0
  animated_text_kit: ^4.2.3
  bloc: ^9.0.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dots_indicator: ^4.0.1
  dotted_border: ^2.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animated_loadingkit: ^0.0.7
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constants
  filename: assets.dart
  field_prefix: null
