name: chat_bot_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  cupertino_icons: ^1.0.8
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  go_router: ^15.1.1
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constants
  filename: assets.dart
  field_prefix: null
